### ISSUE TITLE
Task :app:kspDebugKotlin FAILED, couldn't build the project

### ISSUE THREAD

**Issue by admmq** [Acclorite/book-story#3] opened 2024-06-19 12:18 UTC
Hello. Tried to build this project in Android Studio but got this error. I should put an empty 1.json in the directory. Or there is something else I will need to do? 
> Task :app:kspDebugKotlin FAILED
e: [ksp] C:/Users/user/Downloads/book-story/app/src/main/java/ua/acclorite/book_story/data/local/room/BookDatabase.kt:20: Schema '1.json' required for migration was not found at the schema out folder: C:\Users\user\Downloads\book-story\app\schemas\ua.acclorite.book_story.data.local.room.BookDatabase. Cannot generate auto migrations.
e: Error occurred in KSP, check log for detail
[ksp] C:/Users/user/Downloads/book-story/app/src/main/java/ua/acclorite/book_story/data/local/room/BookDatabase.kt:20: Schema '1.json' required for migration was not found at the schema out folder: C:\Users\user\Downloads\book-story\app\schemas\ua.acclorite.book_story.data.local.room.BookDatabase. Cannot generate auto migrations.

**Comment by Acclorite** [comment] 2024-06-19 12:37
This error seems to be caused by not having **1.json** in your **app/schemas/** which is required to be able to build the app.
It is generated file and was not added to GitHub by default. I will include it in the next commit, I didn't think of it, sorry.

Please unzip and put **[schemas.zip](https://github.com/user-attachments/files/15900868/schemas.zip)** in **[Project Folder]/app/** _(so it looks like [Project Folder]/app/schemas/ua.acclorite..../1.json)_. It should fix build failure and you should be able to successfully build the project.

I will close this issue for now, hope it helps.

**Closed by Acclorite** 2024-06-19 12:37 UTC

**Comment by admmq** [comment] 2024-06-19 12:51
Yep, it helped!
