### ISSUE TITLE
Feature request : ebook with horizontal pages scrolling

### ISSUE THREAD

**Issue by CelianGdfrd** [Acclorite/book-story#25] opened 2024-08-08 18:21 UTC
Hi -- love your work on the reader, the library display, and the possibility to change the font and its size!

I have to say, I really like to read my ebooks by scrolling the pages horizontally, with an elegant display of the text on the screen, to make it look like an actual book. It could lead to more customization, like with the interline, columns or margins.

Would this fit in your plans, please ?

**Comment by Acclorite** [comment] 2024-08-08 18:41
Thank you! 

> Would this fit in your plans, please ?
Yes, but not sure exactly when. Probably when I will finally switch to improving Reader again(gotta lots of todos already).

Duplicate of #13. (Canceled as it is duplicate)

**Closed by Acclorite** 2024-08-08 18:41 UTC

**Comment by CelianGdfrd** [comment] 2024-08-08 20:47
Thanks !! Best of luck with the dev, then ✌️
