### ISSUE TITLE
MemoryException with extra large book(+20m characters)

### ISSUE THREAD

**Issue by lukeallister** [Acclorite/book-story#16] opened 2024-08-06 18:43 UTC
When I try to add a couple books, it says loading and then the app crashes.

I was able to load one book

**Comment by lukeallister** [comment] 2024-08-06 18:51
So I tried again after some time and now it is working. I guess it's fine?

**Comment by Acclorite** [comment] 2024-08-06 18:51
Not sure, **it is not fine** xD, I have everything working.
Can you please specify exact device you use and API(android version).

The app was in fact tested multiple times on every api level, never had this issue.
I would really appreciate detailed information.

**Comment by Acclorite** [comment] 2024-08-06 18:53
If you can tell me exactly steps you have done(eg: Open the app, setting etc), I can test it on the same API level and may be able to reproduce issue.

**Comment by lukeallister** [comment] 2024-08-06 19:43
Haha sure:

- Pixel 7
- release is 1.1.0 installed via neo store

I opened the app, granted storage permissions and chose earth theme with
amoled black.

I went to the library, then went to the explore button bottom right. I
tried to add a bunch of books at once, like 15(?)

The "adding" dialog spun for at least 30 seconds and then the app crashed.

When I opened the app again, my library was still empty.

Then I added one book: success
I added two at once: success
I kept increasing until adding 6 books at once succeeded, at which point I
figured it was probably a first launch problem and replied to the issue

**Comment by Acclorite** [comment] 2024-08-06 19:49
Hmm.. It is okay for the loading to be this long, did you press "Add" button, or it happened while loading?
The quantity of books shouldn't really matter, possibly something went wrong when parsing the book, resulting in crash, what's strange is why it crashed, as the whole process is covered with try { } blocks to prevents crash if error happened.

You did not specify your **Android version**, also if you can, please provide **all** books you have tested first time, or at least **some** of them, so I can try to reproduce. Also the app was tested on Pixel 7, which is also strange.

**Comment by lukeallister** [comment] 2024-08-06 20:11
The crash happened while loading. I never saw an add button

Android 14

I'm not sure which all I tried in that batch, but some would be

- Sanderson mistborn trilogy

- project hail Mary (weir)

- some Harry Potter (3)

- dark Tower books (4)


I just tried it with a big selection (34 books) and it crashed again in the
same way

**Comment by Acclorite** [comment] 2024-08-06 20:20
Please, add files. It seems to be a file error. I cannot fix the issue if no files provided, as all my test books work perfectly.

**Comment by lukeallister** [comment] 2024-08-06 20:23
Aha! I just got it to crash with just one book (that was in the earlier
batches)

Wheel of time collection 17.58 MB

I'm not going to post the file but I can send it to you directly. How would
you like to do that?

**Comment by Acclorite** [comment] 2024-08-06 20:27
Any method you like, you can link gdrive file here(with access through link), or contact me in any social media linked in About screen in the app.

For example, send me a private message on [Reddit](https://www.reddit.com/user/Acclorite/) if you are fine with that.

**Comment by Acclorite** [comment] 2024-08-06 21:19
Was able to reproduce the issue with the file.
Gives an OutOfMemory exception - seems like the book is so large, it cannot parse it at once without memory exception.
That is why it passed through try {} block.

For now, ignore that book.

**Was able to fix**, with `largeHeap=true` in Manifest. Please wait for the next release, for now, ignore this book.

And now..
My largest book is 4.5m characters. This one is 24m characters! It is so big, it takes 0.4gb to just load! No wonder it threw an exception. Although, don't worry it won't lag in Reader, and when reading it takes only ~60mb.

So in the end, it was a memory issue, or rather heap, my bad that I didn't find larger book.

**Comment by Acclorite** [comment] 2024-08-11 10:51
Was fixed in **[Release v1.1.1](https://github.com/Acclorite/book-story/releases/tag/v1.1.1)**.

**Closed by Acclorite** 2024-08-11 10:51 UTC
Labels: 👾 Bug
