### ISSUE TITLE
Add Book-Like Page Turning Animation to the E-Book Reader

### ISSUE THREAD

**Issue by OriginalSimon** [Acclorite/book-story#62] opened 2024-09-03 13:02 UTC
### Why you want this feature to be implemented? Please describe.
I would like a feature to be added to the e-book reader that allows users to turn pages like in a real book. This would enhance the realism and immersion of the reading experience. It could also be more convenient for users who are accustomed to traditional books, making reading on the device more enjoyable.

### Describe the feature you'd like to be implemented
I would like to see the addition of a page-turning feature with an animation that mimics the turning of pages in a physical book. Users should be able to choose how they want to turn pages, either vertically or horizontally, as they would in a real book.

### Describe alternatives you've considered
As an alternative, the app could offer the ability to customize the page-turning animation or even disable it entirely for those who prefer a simpler and quicker transition between pages without effects.

### Additional context
This feature could be useful for users who want to create the atmosphere of reading a physical book on their device. If possible, it would be great to have settings for choosing the type of animation or the speed of page turning.

**Comment by Acclorite** [comment] 2024-09-03 13:39
**Please make sure the Issue does not exist.**
Duplicate of #13.

Also, that is not possible, you can read #13 to understand, though I will provide different approach.

**Closed by Acclorite** 2024-09-03 13:39 UTC
Labels: 🚀 Feature request
